version: '3.8'

services:
  merchandise-service:
    container_name: MerchandiseService
    hostname: merchandise_service
    build: ..
    environment:
      DatabaseConnectionOptions__ConnectionString: "Host=host.docker.internal;Port=5427;Database=merchandise-service;Username=postgres;Password=WQs4##!k7qi0TV0B8!LC3c74pI@oPc#!"
    depends_on:
      - merchandise-service-db
        
  merchandise-service-db:
    image: postgres:latest
    container_name: MerchandiseServiceDb
    ports:
      - "5427:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: WQs4##!k7qi0TV0B8!LC3c74pI@oPc#!
      POSTGRES_DB: merchandise-service
    command: "-c log_statement=all"
      
  stock-api:
    image: 'ghcr.io/ozon-edu-csharp-2021/stock-api:main'
    container_name: StockApi
    hostname: stock_api
    ports:
      - "8080:80"
    
  emailing-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/emailing-service:main'
    container_name: EmailingService
    hostname: emailing_service

  supply-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/supply-service:main'
    container_name: SupplyService
    hostname: supply_service

  employees-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/employees-service:main'
    container_name: EmployeesService
    hostname: employees_service