version: '3.8'

services:
  merchandise-service:
    container_name: MerchandiseService
    hostname: merchandise_service
    build: ..
    ports:
      - "5300:5300"
      - "5302:5302"
    networks:
      - ozon-network
    environment:
      DatabaseConnectionOptions__ConnectionString: "Host=merchandise-service-db;Port=5432;Database=merchandise-service;Username=postgres;Password=WQs4##!k7qi0TV0B8!LC3c74pI@oPc#!"
      StockApiGrpcServiceConfiguration__ServerAddress: "http://stock-api:82"
      KafkaConfiguration__BootstrapServers: "broker:29092"
      KafkaConfiguration__ReplenishedTopic: "stock_replenished_event"
      KafkaConfiguration__ReplenishedGroup: "replenished"
      KafkaConfiguration__EmailNotificationTopic: "email_notification_event"
      KafkaConfiguration__EmployeeNotificationTopic: "employee_notification_event"
      KafkaConfiguration__EmployeeNotificationGroup: "employee"
    depends_on:
      - merchandise-service-db
      - stock-api
      - zookeeper
      - broker
        
  merchandise-service-db:
    image: postgres:latest
    container_name: MerchandiseServiceDb
    hostname: merchandise-service-db
    ports:
      - "5430:5432"
    networks:
      - ozon-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: WQs4##!k7qi0TV0B8!LC3c74pI@oPc#!
      POSTGRES_DB: merchandise-service
    command: "-c log_statement=all"
      
  stock-api:
    image: 'ghcr.io/ozon-edu-csharp-2021/stock-api:main'
    container_name: StockApi
    hostname: stock_api
    ports:
      - "5070:80"
      - "5072:82"
    networks:
      - ozon-network
    environment:
      DatabaseConnectionOptions__ConnectionString: "Host=stock-api-db;Port=5432;Database=stock-api;Username=postgres;Password=stockApiPassword"
      BootstrapServers: "broker:29092"
      topic: "stock_replenished_event"
      groupId: "stock-api-service"
      SupplyApiGrpcServiceConfiguration__ServerAddress: "http://supply-service-api:5082"
    depends_on:
      - stock-api-db
      - redis
      - supply-service-api
      - zookeeper
      - broker
    
  emailing-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/emailing-service:main'
    container_name: EmailingService
    ports:
      - "8555:80"
    depends_on:
      - zookeeper
      - broker
    volumes:
      - emailing-service:/src
    networks:
      - ozon-network

  supply-service-api:
    image: 'ghcr.io/ozon-edu-csharp-2021/supply-service:main'
    container_name: SupplyServiceApi
    ports:
      - "5080:5080"
      - "5082:5082"
    environment:
      DbConfiguration__ConnectionString: "Host=supply-service-db;Port=5432;Database=supply-service;Username=postgres;Password=supplyServicePassword"
      KafkaConfiguration__BootstrapServers: "broker:29092"
    networks:
      - ozon-network
    depends_on:
      - supply-service-db
      - zookeeper
      - broker

  employees-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/employees-service:main'
    container_name: EmployeesService
    ports:
      - "8443:80"
    networks:
      - ozon-network
    environment:
      ConnectionString: "Host=employees-service-postgres-db;Port=5432;Database=employees-service;Username=postgres;Password=postgres;"
      BootstrapServers: "broker:29092"
    depends_on:
      - employees-service-postgres-db
      - zookeeper
      - broker
    volumes:
      - employees-service:/src

  stock-api-db:
    image: postgres:latest
    container_name: StockApiDb
    hostname: stock-api-db
    ports:
      - "5426:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: stockApiPassword
      POSTGRES_DB: stock-api
    command: "-c log_statement=all"
    networks:
      - ozon-network
    volumes:
      - stock-api-db:/var/lib/postgresql/data
  
  supply-service-db:
    image: postgres:latest
    container_name: SupplyServiceDb
    hostname: supply-service-db
    ports:
      - "5427:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supplyServicePassword
      POSTGRES_DB: supply-service
    command: "-c log_statement=all"
    networks:
      - ozon-network
    volumes:
      - supply-service-db:/var/lib/postgresql/data
  
  employees-service-postgres-db:
    image: postgres:latest
    container_name: EmployeeServiceDb
    hostname: employees-service-postgres-db
    ports:
      - "5425:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employees-service
    volumes:
      - employees-service-postgres-db:/var/lib/postgresql/data"
    command: "-c log_statement=all"
    networks:
      - ozon-network
  
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - ozon-network
  
  broker:
    image: confluentinc/cp-kafka:6.2.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - ozon-network
  
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - ozon-network
    hostname: redis
  
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - ozon-network
  
networks:
  ozon-network:
    driver: bridge

volumes:
  ozon-volume:
    driver: local
  employees-service:
    driver: local
  emailing-service:
    driver: local
  stock-api-db:
    driver: local
  supply-service-db:
    driver: local
  employees-service-postgres-db:
    driver: local